# Generated by Django 3.0.14 on 2023-03-06 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderItem',
            new_name='OrderItem',
        ),
    ]
